entities:
  transport:
    - RapidKL
    - KTM
    - KTMB
    - MRT
    - LRT
    - ECRL
    - RTS Link
    - Penang Rapid
    - Rapid Penang
    - Ampang Line
    - Sri Petaling Line
    - Ampang/Sri Petaling Line
    - Ampang and Sri Petaling LRT Lines
    - Kelana Jaya Line
    - Kajang/Putrajaya Lines
    - KL Monorail Line
    - KL Sentral
    - Seremban Line
    - Port Klang Line
    - Skudai Line
    - Butterworth-Padang Besar
    - East Coast Line
  telco_internet:
    - Unifi
    - Maxis
    - CelcomDigi
  banking_payments:
    - Maybank
    - MAE
    - DuitNow
    - CIMB
    - TNG eWallet
  gov_portals:
    - MyJPJ
    - PTPTN
    - KWSP
    - Immigration
    - MyGov
  flood_weather:
    - Kuala Lumpur
    - Selangor
    - Johor
    - Penang
    - Kelantan
    - Sabah
    - Sarawak
    - Kedah
    - Perak
    - Pahang
    - Negeri Sembilan
    - Melaka
    - Terengganu
    - Perlis
    - Labuan
